name: Update New

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update:
    uses: ci-ke/ProjectSekai-BangDream-story-crawler/.github/workflows/common-update.yml@main
    permissions:
      contents: write
    with:
      run_command: "uv run -m action.new_bang"
      commit_message: "Update new"